FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

WORKDIR /usr/src/app

# For testing only.
# Can update the env var and commit to trigger rebuild.
ENV COUNTER 1

COPY start.sh ./

CMD ["bash", "start.sh"]
